# Generated by Django 4.0.1 on 2022-01-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
